"""empty message

Revision ID: 727fecbddd58
Revises: f9392eb5a06c
Create Date: 2026-04-16 11:43:41.118819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727fecbddd58'
down_revision: Union[str, Sequence[str], None] = 'f9392eb5a06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('amenities', sa.String(), nullable=True))
    op.add_column('tours', sa.Column('available_dates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'available_dates')
    op.drop_column('tours', 'amenities')
    # ### end Alembic commands ###
