"""empty message

Revision ID: f9392eb5a06c
Revises: 41d6f817a5e3
Create Date: 2026-04-16 11:08:53.048591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9392eb5a06c'
down_revision: Union[str, Sequence[str], None] = '41d6f817a5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'created_at')
    # ### end Alembic commands ###
